### PR TITLE
21 check vector

### LINKED ISSUE #21: Check if vector is malformed
We should test if vectors meet the standards of the specification. This should prevent the library to throw unexpected errors. For this to work we need a function that tests the following:

1. Are all required metrics included in the vector? 
2. Are there any metrics that are not in the specification?
3. Do all metrics have only possible values? 

For refrence which metrics are required and so on you can take a look [here](https://www.first.org/cvss/v3.0/specification-document#Vector-String).

It might be an idea to make this function available to the end user to quickly test if a vector is valid.

### PR DESCRIPTION
**Pull request by jackson541**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #21  (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Fubinator** [comment]
Hey @jackson541, unfortunately I am sick at the moment. It could take another one or two dass before I get the chance to review your PR. Just to let you know

**Comment by jackson541** [comment]
No problem, @Fubinator . Get well!

File: lib/cvss.js [hunk 1]
```diff
@@ -161,7 +161,83 @@ function CVSS(vector) {
...
+      } else {
+        return serializedAbbr;
+      }
+    }, "");
+
+    const totalExpressionVector = new RegExp("^CVSS:3.0(/" + expression + ")+$");
+
+    //Checks if the vector is in valid format
+    if(!totalExpressionVector.test(vector)){
+      return {
```
Comment (Fubinator) [inline lib/cvss.js:192]: I'm not sure if we should return an object here instead of just true or false. I think in a next step it would be good if the vector is already validated when it is created and if it is invalid, an exception is thrown. In that way we make sure that our vector is always valid and the user can not call the other methods if the vector is invalid. This would save us the effort of securing the other functions, resp. checking in each function if the vector is valid.

Comment (jackson541) [reply lib/cvss.js:192]: ok, my idea with the object was to inform the user why the vector is invalid

Comment (jackson541) [reply lib/cvss.js:192]: So, should I add the initial check to the role when it is created?

Comment (Fubinator) [reply lib/cvss.js:192]: I think the best idea would be to throw an Error if the user calls `CVSS()` with an invalid vector. Maybe we could set a "class-wide" variable indicating if the vector is valid. I do not know how useful this would be, because isValid can never be false.

So for example:
Valid vectors:
```js
const vector = CVSS("CVSS:3.0/AV:L/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L/E:U/RL:T/RC:R")
console.log(vector.isValid) // true
```

And for invalid vectors
```js
const vector = CVSS("CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L/E:U/RL:T/RC:R/RC:R"); // Throws Error with message
```

Comment (jackson541) [reply lib/cvss.js:192]: I think it will be useful only for testing purposes and as a guarantee to the user that everything is correct.

Comment (jackson541) [reply lib/cvss.js:192]: I'll change the code right now, thanks!

Comment (jackson541) [reply lib/cvss.js:192]: the isVectorValid function still needs to be public if it will now have the variable isValid?

Comment (Fubinator) [reply lib/cvss.js:192]: i think you can just use a variable in the "root" CVSS function and provide it to the user, right?

Comment (Fubinator) [reply lib/cvss.js:192]: What I mean is something like
`const isValid = isVectorValid()`

and then provide `isValid` in the object that is returned.

Comment (jackson541) [reply lib/cvss.js:192]: Yes, I have another question, can I run the tests with an error being launched?

Comment (Fubinator) [reply lib/cvss.js:192]: Yes, I think you can use `expect(CVSS("VECTOR")).toThrowError("ERROR_MESSAGE")`

https://jestjs.io/docs/en/expect#tothrowerror

Comment (jackson541) [reply lib/cvss.js:192]: Thank you!

File: index.js [hunk 2]
```diff
@@ -1,3 +1,6 @@
 const CVSS = require("./lib/cvss.js");
 
+const vector = CVSS("CVSS:3.0/AV:L/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L/E:U/RL:T/RC:R");
```
Comment (Fubinator) [inline index.js:3]: I think you forgot to remove this here. Rest ist LGTM!

**Comment by jackson541** [comment]
I found a new error, I will fix it

File: index.js (hunk 2 above)
Comment (jackson541) [reply index.js:3]: Yes hahaha, I forgot to remove

**Review by Fubinator — APPROVED** [review]
This is looking good now. Thank you very much!

**Comment by jackson541** [comment]
Are the comments explaining the code okay? I don't know if it was enough to explain each part

**Comment by Fubinator** [comment]
Yes  @jackson541. I didn't have any issues understanding what your code does with those comments, so they were good!

**Comment by jackson541** [comment]
Thank you!
